module.exports  = {
 states:{
	running:[
	 'created', 
	 'queued', 
	 'received', 
	 'started'
	],
	colors:{
	 //Yellow
	 created:'#F9A825',
	 queued:'#F9A825',
	 received:'#F9A825',
	 started:'#F9A825',
	 //Green
	 passed:'#038955',
	 ready:'#038955',
	 //Red
	 errored:'#D32F2F',
	 failed: '#D32F2F',
	 //Grey
	 canceled:'#757575'
	},
	icons:{
	 //Yellow
	 created:'timer-sand',
	 queued:'timer-sand',
	 received:'timer-sand',
	 started:'timer-sand',
	 //Green
	 passed:'check',
	 ready:'check',
	 //Red
	 errored:'window-close',
	 failed: 'window-close',
	 //Grey
	 canceled:'cancel'
	},
 } 
}
